version: "3.8"
services:
  db:
    image: mysql:8
    container_name: vstep_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vstep_db
    ports:
      - "3306:3306"
    volumes:
      - ./database/data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: vstep_backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - NODE_ENV=development

  frontend:
    build: ./frontend
    container_name: vstep_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
